version: '3.8'

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    # image: hra4h03/nestjs-build
    container_name: nestjs-permission
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - local-network

networks:
  local-network:
    name: local-network
    external: true
